### PR TITLE
Updates for latest StageXL release

### PR DESCRIPTION
**Pull request by bp74**
Hi Alex,

I did a few updates to the RichTextField library to work with the latest StageXL release. It would be great if you could merge this changes and do a "pub publish".

Thanks a lot,
Bernhard

### CODE REVIEW

**Comment by alexgann** [comment]
Thanks Bernhard!  Unfortunately the project I was using dart/stagexl for isn't happening.  Since you have fully maintained this extension the last two times (thanks for that), would you be amenable to the idea that I transfer ownership of this repo to bp74 and change the pub uploader to whichever email address you prefer?

**Comment by bp74** [comment]
Hi Alex,

I'm sorry to hear that your Dart project didn't come to life. Of course i would be happy to continue the support for this great library. I do all my uploads to pub with the email address support@stagexl.org. If you can manage to upload the new package or just add this email address i can take it from there on.

Best greetings,
Bernhard

**Comment by alexgann** [comment]
Thanks Bernhard - update is uploaded https://pub.dartlang.org/packages/stagexl_richtextfield and your email added as an uploader for the pub package.

Thanks again for being awesome!

**Comment by alexgann** [comment]
(also made you an owner of this repo - feel free to clone to your own repo at some point and I'll shut this was down)

**Comment by bp74** [comment]
Okay that worked great. I moved your repository to my GitHub account. I also tried an upload to Pub which worked fine too - i wonder why does Pub know that i'm a legit uploader of this package? The pubspec.yaml file does not contain my email address.

**Comment by alexgann** [comment]
I added you with `pub uploaded add support@stagexl.org` - feel free to update the pubspec with your repo/info. 

Thanks again!

**Comment by bp74** [comment]
ah okay! i didn't know that this is possible :)

**Pull request merged**
